### PR TITLE
Fix the log duplication issue for --log-file.

### LINKED ISSUE #53: Repeated trace in log file with error
/kind bug

**What steps did you take and what happened:**
https://play.golang.com/p/6l8KNG_iOsM

Configuring klog to write to a file and logtostderr=false, the log file is openned and wrote three times with the same content.

Removing the flush, writes three times the headers, but no content.

**What did you expect to happen:**
Only one open and write.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by yuwenma**
**What this PR does / why we need it**:
We noticed that when a service/app is using the --log-file flag, there could be a severe performance regression due to the duplicated logs generated in log severity cascading (e.g. Error level Log is also tracked and stored in Warning and Info level log). This not only generates duplicate logs in the destination log-file, but also slow down the log-file flush. This PR is specifically adjusting the klog behavior when --log-file is used, and not aimed at providing a generic solution about the log severity cascading or other klog improvements. 
 
For more context, see kubernetes/kubernetes#77904

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #53 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: klog.go [hunk 1]
```diff
@@ -418,7 +418,7 @@ func InitFlags(flagset *flag.FlagSet) {
 	flagset.BoolVar(&logging.alsoToStderr, "alsologtostderr", false, "log to standard error as well as files")
 	flagset.Var(&logging.verbosity, "v", "number for the log level verbosity")
 	flagset.BoolVar(&logging.skipHeaders, "skip_headers", false, "If true, avoid header prefixes in the log messages")
-	flagset.BoolVar(&logging.skipLogHeaders, "skip_log_headers", false, "If true, avoid headers when opening log files")
+	flagset.BoolVar(&logging.skipLogHeaders, "skip_log_headers", false, "If true, avoid headers when openning log files")
```
Comment (tallclair) [inline klog.go]: actually `opening` is correct.

File: klog.go [hunk 2]
```diff
@@ -793,23 +775,52 @@ func (l *loggingT) output(s severity, buf *buffer, file string, line int, alsoTo
...
+	// Note: The stats estimate logs for each severity level individually,
+	// even in the situation that log-file is specified and
+	// all severity-level logs are tracked only in the infoLog file.
 	if stats := severityStats[s]; stats != nil {
 		atomic.AddInt64(&stats.lines, 1)
 		atomic.AddInt64(&stats.bytes, int64(len(data)))
 	}
 }
 
+//writeToDifferentSeverity writes |data| to the `s` and its lower severity file.
```
Comment (tallclair) [inline klog.go]: nit: space after //

Comment (tallclair) [inline klog.go]:
```suggestion
// writeToDifferentSeverity writes |data| to the `s` and lower severity files.
```

File: klog.go [hunk 3]
```diff
@@ -793,23 +775,52 @@ func (l *loggingT) output(s severity, buf *buffer, file string, line int, alsoTo
...
+// e.g. If Severity level is Error, the data will be written to all the Error,
+// Warning, and Info log file. However, if --log_file flag is provided, klog
+// no longer tracks logs separately due to their severity level, but rather
+// only write to the info logfile which later on will be flushed to the
+// dedicated log_file.
+func (l *loggingT) writeToDifferentSeverity(s severity, data []byte) {
```
Comment (tallclair) [inline klog.go]: I recommend factoring this a bit differently:

Make the function:
```go
func (l *logging.T) writeLogData(s severity, data byte) {
  if l.shouldLogToStderr(s) { ... }
  if l.logFile != "" {
    ... // handle single-file mode
  } else {
    ... // handle multi-file mode
  }
}
```

Comment (yuwenma) [reply klog.go]: Sure. but it will have many duplicate code. Is that okay?

Comment (tallclair) [reply klog.go]: I don't think it will have too much. I'm worried that the current approach of defaulting to the info log is too error-prone, and folding in the log-to-stderr functionality will actually deduplicate code (and fix a bug) in the fatal log path.

File: klog.go [hunk 4]
```diff
@@ -756,25 +756,7 @@ func (l *loggingT) output(s severity, buf *buffer, file string, line int, alsoTo
 		if alsoToStderr || l.alsoToStderr || s >= l.stderrThreshold.get() {
 			os.Stderr.Write(data)
 		}
```
Comment (tallclair) [inline klog.go]: Move this block into `writeLogData` too

File: klog.go [hunk 5]
```diff
@@ -793,23 +775,54 @@ func (l *loggingT) output(s severity, buf *buffer, file string, line int, alsoTo
...
 
+// writeLogData writes |data| to the `s` and lower severity files.
+// e.g. If Severity level is Error, the data will be written to all the Error,
+// Warning, and Info log file. However, if --log_file flag is provided, klog
+// no longer tracks logs separately due to their severity level, but rather
+// only write to the info logfile which later on will be flushed to the
+// dedicated log_file.
+func (l *loggingT) writeLogData(s severity, data []byte) {
+	if l.logFile != "" { // single-file mode
+		if l.file[infoLog] == nil {
```
Comment (tallclair) [inline klog.go]: Can we use a dedicated buffer for this, rather than repurposing infoLog?

File: klog.go [hunk 6]
```diff
@@ -793,23 +775,54 @@ func (l *loggingT) output(s severity, buf *buffer, file string, line int, alsoTo
...
+			if err := l.createFiles(infoLog); err != nil {
+				os.Stderr.Write(data) // Make sure the message appears somewhere.
+				l.exit(err)
+			}
+		}
+		if f := l.file[infoLog]; f != nil { // Can be nil if -logtostderr is set.
```
Comment (tallclair) [inline klog.go]: > Can be nil if -logtostderr is set

Why? If `--log-file` is specified, I'd always expect it to write to the file. I think this is https://github.com/kubernetes/klog/issues/54, and we might as well fix it here.

File: klog.go [hunk 7]
```diff
@@ -952,18 +965,30 @@ const bufferSize = 256 * 1024
...
 func (l *loggingT) createFiles(sev severity) error {
 	now := time.Now()
-	// Files are created in decreasing severity order, so as soon as we find one
-	// has already been created, we can stop.
-	for s := sev; s >= infoLog && l.file[s] == nil; s-- {
+	if l.logFile != "" { // single-file mode
 		sb := &syncBuffer{
 			logger:   l,
-			sev:      s,
+			sev:      infoLog,
```
Comment (tallclair) [inline klog.go]: What is this field used for, when in single file mode? Can it be left unset?

File: klog.go [hunk 8]
```diff
@@ -952,18 +965,30 @@ const bufferSize = 256 * 1024
...
 			maxbytes: CalculateMaxSize(),
 		}
 		if err := sb.rotateFile(now, true); err != nil {
```
Comment (tallclair) [inline klog.go]: This is sort of weird, since it's not actually rotating the files in single-file mode. I guess it's fine for now though.

File: klog.go (hunk 4 above)
Comment (yuwenma) [reply klog.go]: The writeLogData is also used in fatal error (see below "if s == fatalLog"), moving the "tostderr" block inside writeLogData will add unwanted log messages. I can try using a flag param, like "fatalerror".

File: klog.go (hunk 6 above)
Comment (yuwenma) [reply klog.go]: I see what the confusion is. The stderr flag looks weird to me, didn't know there's an open issue for that.

File: klog.go (hunk 5 above)
Comment (yuwenma) [reply klog.go]: Agree we shouldn't repurpose infolog. But I also have some concerns to use a dedicated buffer:
I want to patch a quick/safe fix to the log duplicate problem and catch the 1.15 release. Defining a new buffer results in much more complicated changes and it should have longer testing time before imported to kubernetes/kubernetes.

Updated the code with a dedicated buffer for single mode. Let me know if that's the reasonable approach and is safe to go in. If not, I'd prefer a quick fix that touches the least code.

**Comment by dims** [comment]
@tallclair happy with this?
