### PR TITLE
klogr verbosity

### LINKED ISSUE #294: klog always logs verbosity 0 with component-base/logs
/kind bug

**What steps did you take and what happened:**

I'm currently trying to use `component-base/logs` in combination with controller-runtime in ClusterAPI (https://github.com/kubernetes-sigs/cluster-api/pull/6072).
When using `--logging-format=json` the log lines contain `v: 0` independent of the log level with which the line is actually logged.

**What did you expect to happen:**
Should log the verbosity with which the log line is logged.

**Anything else you would like to add:**
When component-base/logs the "log hierarchy" is roughly go-logr.Logger => klog => JSON logger (component-base/logs) => zap:
image

I think the log level get's lost here: https://github.com/kubernetes/klog/blob/main/klogr/klogr.go#L169-L173

**To reproduce**:
I've created a minimal controller here: https://github.com/sbueringer/cr-klog-issue (with k8s.io/component-base v0.23.3 and	k8s.io/klog/v2 v2.40.1)
The issue can be reproduced by running the controller against an arbitrary cluster (with Pods) via:
```
$  go run main.go --logging-format=json --v=4
...
{"ts":1644841271031.652,"caller":"cr-klog-issue/main.go:92","msg":"controller/pod: Verbosity 0","v":0,"reconciler group":"","reconciler kind":"Pod","name":"capi-kubeadm-control-plane-controller-manager-9769796f6-l8nf2","namespace":"capi-kubeadm-control-plane-system"}
{"ts":1644841271031.67,"caller":"cr-klog-issue/main.go:93","msg":"controller/pod: Verbosity 1","v":0,"reconciler group":"","reconciler kind":"Pod","name":"capi-kubeadm-control-plane-controller-manager-9769796f6-l8nf2","namespace":"capi-kubeadm-control-plane-system"}
{"ts":1644841271031.679,"caller":"cr-klog-issue/main.go:94","msg":"controller/pod: Verbosity 2","v":0,"reconciler group":"","reconciler kind":"Pod","name":"capi-kubeadm-control-plane-controller-manager-9769796f6-l8nf2","namespace":"capi-kubeadm-control-plane-system"}
{"ts":1644841271031.6858,"caller":"cr-klog-issue/main.go:95","msg":"controller/pod: Verbosity 3","v":0,"reconciler group":"","reconciler kind":"Pod","name":"capi-kubeadm-control-plane-controller-manager-9769796f6-l8nf2","namespace":"capi-kubeadm-control-plane-system"}
{"ts":1644841271031.693,"caller":"cr-klog-issue/main.go:96","msg":"controller/pod: Verbosity 4","v":0,"reconciler group":"","reconciler kind":"Pod","name":"capi-kubeadm-control-plane-controller-manager-9769796f6-l8nf2","namespace":"capi-kubeadm-control-plane-system"}
```

xref: Slack thread: https://kubernetes.slack.com/archives/CG3518SFJ/p1644596428193789

### PR DESCRIPTION
**Pull request by pohly**
**What this PR does / why we need it**:

klogr must pass through the verbosity level in case that the underlying backend logger cares about it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #294 

**Special notes for your reviewer**:

The first commit enhances the output test so that it shows the bug. zapr is needed for that and the test also gets enhanced to support output mapping better.

The second commit then has the actual bug fix and shows that the test now works without a workaround.

**Release note**:
```release-note
klogr did not pass the verbosity through to klog, which caused loggers such as zapr to just record v=0.
```

### CODE REVIEW

File: test/output.go [hunk 1]
```diff
@@ -686,3 +699,230 @@ func (e *customErrorJSON) Error() string {
...
+
+// ZaprOutputMappingIndirect provides a mapping from klog output to the
+// corresponding zapr output when zapr is called indirectly through
+// klog.
+//
+// This is different from ZaprOutputMappingDirect because:
+// - WithName gets added to the message by Output.
+// - WithValues are part of the normal key/value parameters,
+//   which puts them after "v".
+// - There are no separate warnings about WithValue parameters.
```
Comment (pohly) [inline test/output.go:863]: ... when using zap directly.

I need to make that comment clearer. It might also make sense to add that to zapr, for consistency -> https://github.com/go-logr/zapr/issues/51

File: test/output.go [hunk 2]
```diff
@@ -686,3 +699,230 @@ func (e *customErrorJSON) Error() string {
...
+`: `{"caller":"test/output.go:<LINE>","msg":"test","firstKey":1,"v":0}
+{"caller":"test/output.go:<LINE>","msg":"test","firstKey":1,"secondKey":2,"v":0}
+{"caller":"test/output.go:<LINE>","msg":"test","firstKey":1,"v":0}
+{"caller":"test/output.go:<LINE>","msg":"test","firstKey":1,"secondKey":3,"v":0}
+`,
+
+		`I output.go:<LINE>] "odd WithValues" keyWithoutValue="(MISSING)"
+I output.go:<LINE>] "odd WithValues" keyWithoutValue="(MISSING)" anotherKeyWithoutValue="(MISSING)"
+I output.go:<LINE>] "odd WithValues" keyWithoutValue="(MISSING)"
+`: `{"caller":"test/output.go:<WITH-VALUES>","msg":"odd number of arguments passed as key-value pairs for logging","ignored key":"keyWithoutValue"}
```
Comment (pohly) [inline test/output.go:785]: /hold

Let me double-check why these warnings are printed. They should appear when zapr is called indirectly, but not when used directly.

File: test/output.go (hunk 1 above)
Comment (pohly) [reply test/output.go:863]: It's the other way around: [zapr emits a warning](https://github.com/go-logr/zapr/blob/517e434e7dd06b6a09644da072c246db038a8c62/zapr.go#L145), [klog doesn't](https://github.com/kubernetes/klog/blob/b7a44e3874816d2b62aee5947c4241e316db14b7/internal/serialize/keyvalues.go#L61-L65).

Should we add that to klog?

File: test/output.go (hunk 2 above)
Comment (pohly) [reply test/output.go:785]: /hold cancel

File: .github/workflows/test.yml [hunk 3]
```diff
@@ -18,7 +18,8 @@ jobs:
       run: |
         go get -t -v ./...
         go test -v -race ./...
-        cd hack/tools && go test -v -race ./...
+        cd hack/tools && go test -v -race ./... && cd ../..
```
Comment (thockin) [inline .github/workflows/test.yml:21]: this will fail to `cd ../..` if any test fails, ensuring the next step fails, too

Comment (pohly) [reply .github/workflows/test.yml:21]: I was using `(cd hack/tools && go test -v -race ./...)` earlier, but that failed in Windows. The shell there doesn't seem to support sub-shells.

Is there an absolute path that can be used here?

**Review by thockin — COMMENTED** [review]
Functional change seems appropriate, I didn't read the tests too hard.

File: .github/workflows/test.yml (hunk 3 above)
Comment (thockin) [reply .github/workflows/test.yml:21]: `cd hack/tools && go test -v -race ./... ; cd ../..` ?

`sh -c "cd hack/tools && go test -v -race ./..."` ?

FWIW https://github.com/golang/go/issues/50332
