### PR TITLE
Fix byte array display in InfoS and ErrorS

### LINKED ISSUE #236: []byte will use +%v through InfoS.
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
klog.InfoS("[]byte", "b1", []byte("hello world"))
```
print:
I0508 19:35:13.452661   57319 testKlog.go:11] "[]byte" b1=[104 101 108 108 111 32 119 111 114 108 100]

**What did you expect to happen:**
I0508 19:37:01.473191    2045 testKlog.go:11] "[]byte" b1="hello world"

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
part of https://github.com/kubernetes/kubernetes/issues/101714
As k8s conducts structured log migration, `InfoS `is used more and more, but` []byte`, usually cooperates with %q `before `the migration, is it necessary to submit a PR so that []byte uses %q in InfoS?
Currently in InfoS, []byte uses %+v.
https://github.com/kubernetes/klog/blob/0cc9b8363efc89db73313bf618deeff8964c4a86/klog.go#L832
If the idea is approved, I will do it, otherwise I will probably continue to use `klog.InfoS("[]byte", "b1", string([]byte("hello world")))`.

### PR DESCRIPTION
**Pull request by yuzhiquan**
**What this PR does / why we need it**:
Fix byte array display in InfoS and ErrorS
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #236 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yuzhiquan** [comment]
refs https://github.com/kubernetes/kubernetes/issues/101714

File: klog_test.go [hunk 1]
```diff
@@ -1067,6 +1067,10 @@ func TestKvListFormat(t *testing.T) {
 			keysValues: []interface{}{"pod", "kubedns", "values", []string{"deployment", "svc", "configmap"}},
 			want:       " pod=\"kubedns\" values=[deployment svc configmap]",
 		},
+		{
+			keysValues: []interface{}{"pod", "kubedns", "[]byte", []byte("test for byte array")},
```
Comment (serathius) [inline klog_test.go:1071]: Can you change the name of the key `[]byte`. It's doesn't match our naming conventions and it's easy to confuse with type. Just `bytes` should be good.

**Comment by dims** [comment]
@yuzhiquan what if the byte array has non-printable characters?

**Comment by yuzhiquan** [comment]
> non-printable characters

@dims As showed here https://blog.golang.org/strings#TOC_3. may be plus %q is ok for non-printable characters
