### PR TITLE
Fix rotate file

### LINKED ISSUE #171: use log_file_max_size,if restart cannot rotate file logfile ,logfile > log_file_max_size
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
If --log_file_max_size=1
Setting logMaxSize 1MB running for a period of time logfile size 0.9MB 
then restart
logfile > 1MB not raote

**What did you expect to happen:**

logfile <= 1MB

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by bamboox**
**What this PR does / why we need it**:
when restart log_file_max_size args invalid

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #171 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Fix use --log_file_max_size，Restart after running for a period of time, the log_file_size larger than the set value
```

### CODE REVIEW

File: klog.go [hunk 1]
```diff
@@ -1077,7 +1077,17 @@ func (sb *syncBuffer) rotateFile(now time.Time, startup bool) error {
 	}
 	var err error
 	sb.file, _, err = create(severityName[sb.sev], now, startup)
-	sb.nbytes = 0
+	if startup {
+		fileInfo, err := sb.file.Stat()
+		if err != nil {
+			return err
```
Comment (neolit123) [inline klog.go:1083]: does this need a slightly more descriptive error message - e.g. `fmt.Errorf("..... could not ....: %v, err)`?

**Comment by neolit123** [comment]
thank you for the PR, i've added one comment above.

also please sign the CLA if you haven't already (see the bot comment)
and under `Release note:` add a short but descriptive explanation about the fix.
