### PR TITLE
Recover from nil pointers when logging

### LINKED ISSUE #278: segfault for nil fmt.Stringer
/kind bug

**What steps did you take and what happened:**

Unit tests in Kubernetes segfault (https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/107103/pull-kubernetes-unit/1471877384482328576/build-log.txt):

```
testing.tRunner.func1.2({0x517fd60, 0x8aa1f60})
	/usr/local/go/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x3b6
panic({0x517fd60, 0x8aa1f60})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
k8s.io/kubernetes/pkg/kubelet/container.(*RuntimeCondition).String(0x0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/container/runtime.go:528 +0x59
k8s.io/kubernetes/vendor/k8s.io/klog/v2.kvListFormat(0xc0000251f0, {0xc000c08620, 0x2, 0x5925698})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:850 +0x453
```

**What did you expect to happen:**

We probably need to emulate what `fmt.Sprintf("%q", <nil stringer>)` did - whatever that is.

### PR DESCRIPTION
**Pull request by dims**
we used to rely on `fmt.Sprintf` which was handling the nil pointers for us. With the latest changes we avoid using `fmt.Sprintf` for speed/performance, So let's use a `recover` to survive the `panic`.

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #278

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
fixes a problem handling nil pointers when logging
```

### CODE REVIEW

File: klog.go [hunk 1]
```diff
@@ -872,6 +872,16 @@ func kvListFormat(b *bytes.Buffer, keysAndValues ...interface{}) {
...
 }
 
+func StringertoString(s fmt.Stringer) (ret string) {
+	defer func() {
+		if err := recover(); err != nil {
+			ret = "nil"
+		}
+	}()
+	ret = s.String()
+	return ret
```
Comment (pohly) [inline klog.go:882]: This indeed the same as what fmt.Sprintf does: https://go.dev/play/p/i4I-vYc4qJi

It calls String() and only falls back to "nil" when that panics.

File: klog.go [hunk 2]
```diff
@@ -872,6 +872,16 @@ func kvListFormat(b *bytes.Buffer, keysAndValues ...interface{}) {
 	}
 }
 
+func StringertoString(s fmt.Stringer) (ret string) {
```
Comment (pohly) [inline klog.go:875]: nil: should that be `StringerToString`?

Comment (pohly) [reply klog.go:875]: More important: should that function be exported and thus be part of the klog API?

I prefer to keep it internal.

Comment (dims) [reply klog.go:875]: will switch it to `stringertoString`

File: klog.go (hunk 1 above)
Comment (dims) [reply klog.go:882]: yep

**Comment by dims** [comment]
@pohly thanks! resolved all the conversations

**Review by pohly — APPROVED** [review]
/lgtm
