### PR TITLE
Do not acquire lock for file.Sync() fsync call

### LINKED ISSUE #403: When disk I/O was very heavy, klog calling file sync with locking caused all log recording to be blocked for a long time.
/kind bug

**What steps did you take and what happened:**

We found an issue in our Kubernetes cluster. When disk I/O was very heavy, the node would occasionally become not ready.
We identified that this was because klog was calling fsync with locking, which caused kubelet's log writing to be blocked. This resulted in the container runtime status check time exceeding 10 seconds. As a result, kubelet considered the container runtime to be unhealthy and set the node to not ready status.

The kernel has an excellent and efficient buffered I/O mechanism. fsync can ensure that logs are persisted to disk, but we should not call fsync with locking as it would significantly impact performance and fail to take advantage of the kernel's buffered I/O mechanism, making it no different from using direct I/O (which is generally only used by databases).

A high-performance approach is to spawn a lock-free goroutine to periodically call fsync.(fsync does not block buffered I/O)

https://github.com/kubernetes/klog/blob/main/klog.go#L1224

``` go
// lockAndFlushAll is like flushAll but locks l.mu first.
func (l *loggingT) lockAndFlushAll() {
	l.mu.Lock()
	l.flushAll()
	l.mu.Unlock()
}

// flushAll flushes all the logs and attempts to "sync" their data to disk.
// l.mu is held.
func (l *loggingT) flushAll() {
	// Flush from fatal down, in case there's trouble flushing.
	for s := severity.FatalLog; s >= severity.InfoLog; s-- {
		file := l.file[s]
		if file != nil {
			_ = file.Flush() // ignore error
			_ = file.Sync()  // ignore error
		}
	}
	if logging.loggerOptions.flush != nil {
		logging.loggerOptions.flush()
	}
}
```

**What did you expect to happen:**

klog will not block normal log recording due to flushing dirty pages to disk(heavy IO).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by 1978629634**
**What this PR does / why we need it**:

For file.Sync() (the fsync system call that flushes the kernel buffer to disk), there is no need to acquire a lock; let the kernel handle it.

**Which issue(s) this PR fixes**:

Fixes #403 

**Release note**:

```release-note
Do not acquire lock for file.Sync() fsync call
```

### CODE REVIEW

**Comment by 1978629634** [comment]
Hi @harshanarayana @mengjiao-liu , Could you please take a look at this pull request when you have a chance? I'd appreciate your review and feedback.

File: klog.go [hunk 1]
```diff
@@ -1223,26 +1223,39 @@ func StartFlushDaemon(interval time.Duration) {
...
 	l.mu.Lock()
+	// Write the klog buffer into the kernel buffer
 	l.flushAll()
 	l.mu.Unlock()
+	// Write the kernel buffer to disk
+	l.syncAll()
 }
 
-// flushAll flushes all the logs and attempts to "sync" their data to disk.
+// FlushAll flushes all the logs
```
Comment (dims) [inline klog.go:1233]: `flushAll` NOT `FlushAll`

Comment (1978629634) [reply klog.go]: Thank you for taking the time to help review the code. I have finished making the modifications.

**Comment by 1978629634** [comment]
> xref: [golang#68](https://github.com/golang/glog/pull/68)
Could you please review it again?

**Comment by 1978629634** [comment]
> > xref: [golang#68](https://github.com/golang/glog/pull/68)
> 
> Could you please review it again?

The changes to the glog have a potential issue. Besides the FlushDaemon, there is also an exit() call that invokes flushAll. If we release the lock and call file.Sync() in the exit code, the program may continue to write logs, which could lead to the program running longer than expected.
In the exit(), we should acquire the lock and call file.Sync() to ensure a clean shutdown.
cc @dims

**Comment by 1978629634** [comment]
@pohly I'd appreciate it if you could take a look at this pull request and offer any suggestions you may have. Your feedback would be invaluable. Thank you so much!

**Comment by pohly** [comment]
I have it on my TODO list, but it may take a while before I get to it.

**Review by logicalhan — COMMENTED** [review]
/triage accepted
/assign @pohly

File: klog.go [hunk 2]
```diff
@@ -1225,24 +1226,36 @@ func (l *loggingT) lockAndFlushAll() {
...
 	if logging.loggerOptions.flush != nil {
 		logging.loggerOptions.flush()
 	}
 }
 
+// syncAll attempts to "sync" their data to disk.
+func (l *loggingT) syncAll() {
+	// Flush from fatal down, in case there's trouble flushing.
+	for s := severity.FatalLog; s >= severity.InfoLog; s-- {
+		file := l.file[s]
```
Comment (pohly) [inline klog.go:1252]: I think accessing `l.file[s]` must be protected by the mutex. So lock the mutex, collect all non-nil files in a slice, then unlock and sync them.

Comment (pohly) [reply klog.go:1252]: You could let `flushAll` return a slice of open files. Then pass that into `syncAll` and use it there without locking.

**Review by pohly — APPROVED** [review]
/lgtm
/approve

File: klog.go [hunk 3]
```diff
@@ -1223,24 +1224,38 @@ func StartFlushDaemon(interval time.Duration) {
...
 	}
+	return files
+}
+
+// syncAll attempts to "sync" their data to disk.
+func (l *loggingT) syncAll(files []flushSyncWriter) {
+	// Flush from fatal down, in case there's trouble flushing.
+	for _, file := range files {
+		if file != nil {
+			_ = file.Sync() // ignore error
```
Comment (pohly) [inline klog.go:1256]: As noted in https://github.com/kubernetes/klog/issues/403#issuecomment-2035397706, `syncBuffer` is not thread-safe and here we call `syncBuffer.Sync`.

Will follow-up in https://github.com/kubernetes/klog/issues/407.
