### PR TITLE
Fix Windows integration tests

### LINKED ISSUE #133: investigate windows unit test failures
/kind feature
/help
/good-first-issue

- run `GOOS=windows go test ./...` and see why the tests fail on windows.
- fix the tests.
- add `windows-latest` in the list of of OSes here:
https://github.com/kubernetes/klog/blob/master/.github/workflows/test.yml#L8
- send a PR

### PR DESCRIPTION
**Pull request by sebsoto**
**What this PR does / why we need it**:

This PR fixes issues with Windows integration tests and enables the
tests to run through github. The problem was that the tests using the
log_dir option expected symlinks to the log files to exist, those
symlinks being (main.INFO, main.WARN, etc). This was a problem for
two reasons:

1) On Windows the symlinks would start with main.exe, not just main
2) The creation of symlinks is not guarenteed on any platform, and on
Windows creating a symlink requires Administrator permissions.

This was fixed by changing the tests to search for either the symlinks
(with a fixed filepath), or the log files themselves.

Future work can be done to deal with the lack of symlinks on Windows,
but this PR's purpose is to get tests in a passing state.

Also includes changes from #137 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #133 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: integration_tests/klog_test.go [hunk 1]
```diff
@@ -214,13 +225,19 @@ func TestDestinationsWithDifferentFlags(t *testing.T) {
 				}
 
 				// check files in log_dir
-				for level, file := range logFileName {
-					logfile := filepath.Join(logdir, file) // /some/tmp/dir/main.WARNING
+				for level, levelName := range logFileLevels {
+					binaryName := "main" + binaryFileExtention
```
Comment (neolit123) [inline integration_tests/klog_test.go:229]: we can move the `binaryFileExtention` variable definition in `TestDestinationsWithDifferentFlags` for now.

File: integration_tests/klog_test.go [hunk 2]
```diff
@@ -306,3 +323,30 @@ func withTmpDir(t *testing.T, f func(string)) {
...
+	}
+	files, err := ioutil.ReadDir(dir)
+	if err != nil {
+		return "", fmt.Errorf("could not read directory %s: %v", dir, err)
+	}
+	var foundFile string
+	for _, file := range files {
+		if strings.HasPrefix(file.Name(), binaryName) && strings.Contains(file.Name(), levelName) {
+			if foundFile != "" {
+				return "", fmt.Errorf("found multiple matching files")
```
Comment (neolit123) [inline integration_tests/klog_test.go:343]: shouldn't we be matching the filename exactly instead of matching by HasPrefix and Contains and accounting for multiple matches?

i.e. `if file == binaryName {`

**Comment by neolit123** [comment]
thanks for sending the PR for this, @sebsoto 
i've added a couple of comments.

please, note that sometimes the tests flake randomly.

File: integration_tests/klog_test.go (hunk 2 above)
Comment (sebsoto) [reply integration_tests/klog_test.go:341]: I dont think that would be possible. The filename is generated like this: https://github.com/kubernetes/klog/blob/4cae117fdf5d65aeb3f638b8d8c87cd1cf8c8d41/klog_file.go#L97
```
	name = fmt.Sprintf("%s.%s.%s.log.%s.%04d%02d%02d-%02d%02d%02d.%d",
		program,
		host,
		userName,
		tag,
		t.Year(),
		t.Month(),
		t.Day(),
		t.Hour(),
		t.Minute(),
		t.Second(),
		pid)
```

The best we could do would be constructing a larger prefix `program.host.userName.logLevel`. That way the `strings.Contains()` call can be removed. That would come at the cost of having to re-implement the`[shortHostname ](https://github.com/kubernetes/klog/blob/4cae117fdf5d65aeb3f638b8d8c87cd1cf8c8d41/klog_file.go#L88) function within the  test file though.

I'm not sure what would be preferable.

**Comment by sebsoto** [comment]
Thanks @neolit123, I've pushed a change in response to one of your comments and replied to the other.

>please, note that sometimes the tests flake randomly
Running into this now, with `TestRollover`, not seeing it locally.

File: integration_tests/klog_test.go (hunk 2 above)
Comment (neolit123) [reply integration_tests/klog_test.go:340]: hm, yet the original code matched a filename exactly using `assertFileIsAbsent` and `logfile := filepath.Join(logdir, file)`

i'm trying to understand why this is a problem on windows.

other options:
- wouldn't `withTmpDir` ensure that the temp directory where the logs are stored contain only a single file matching the level?
- looks like the filename ends with a pid, can that be used for match too?

Comment (sebsoto) [reply integration_tests/klog_test.go:340]: >wouldn't withTmpDir ensure that the temp directory where the logs are stored contain only a single file matching the level?
Under properly working circumstances yes it should. I included the check on the off chance that something went wrong, like multiple log files for the same level being used.

Comment (neolit123) [reply integration_tests/klog_test.go:340]: ok let's leave this as is for now, unless someone else objects.

**Comment by neolit123** [comment]
> Running into this now, with TestRollover, not seeing it locally.

i think it happen very rarely for me when testing on Windows.
i didn't dig too much but the issue appeared to be related to aggressive timeouts.

looks like the tests are racing as well:
> ##[error]    TestOpenAppendOnStart: testing.go:906: race detected during execution of test

https://github.com/kubernetes/klog/pull/136/checks?check_run_id=574960371

**Comment by lsytj0413** [comment]
> Thanks @neolit123, I've pushed a change in response to one of your comments and replied to the other.
> 
> > please, note that sometimes the tests flake randomly
> 
> Running into this now, with `TestRollover`, not seeing it locally.

The TestRollover failed most every time on my windows env.

**Comment by lsytj0413** [comment]
> Thanks @neolit123, I've pushed a change in response to one of your comments and replied to the other.
> 
> > please, note that sometimes the tests flake randomly
> 
> Running into this now, with `TestRollover`, not seeing it locally.

I found this was cased by TestSetOutputDataRace function，it called SetOutputBySeverity/SetOutput in another goroutine which maybe change INFO level logfile to redirectBuffer after TestSetOutputDataRace done。This behavior broken  TestRollover randomly。

**Comment by lsytj0413** [comment]
> > Thanks @neolit123, I've pushed a change in response to one of your comments and replied to the other.
> > > please, note that sometimes the tests flake randomly
> > 
> > 
> > Running into this now, with `TestRollover`, not seeing it locally.
> 
> I found this was cased by TestSetOutputDataRace function，it called SetOutputBySeverity/SetOutput in another goroutine which maybe change INFO level logfile to redirectBuffer after TestSetOutputDataRace done。This behavior broken TestRollover randomly。

I will open a prototype PR for this。

**Comment by neolit123** [comment]
@sebsoto please take a look at the change from @lsytj0413 and add it in your PR to test windows with it. thanks!

**Comment by sebsoto** [comment]
@neolit123 Added the commit from @lsytj0413. All tests are passing now :tada:

**Comment by dims** [comment]
/approve

(@neolit123 please apply lgtm)

**Comment by neolit123** [comment]
we need to enable `/retest` to work for actions too.
/hold cancel
