### PR TITLE
Fix logcheck exit function

### LINKED ISSUE #264: logcheck doesn't handle Exit* functions correctly
/kind bug

klog defines set of functions Exit, Exitf, Exitln, ExitDepth. Those functions are not correctly handled by logcheck. https://github.com/kubernetes/kubernetes/pull/103293#issuecomment-885028839

**What steps did you take and what happened:**

When running logcheck to validate log calls, it reported Exitf as structured logging method
```
/home/prow/go/src/k8s.io/kubernetes/test/images/apparmor-loader/loader.go:64:3: structured logging function "Exitf" should not use format specifier "%s"
```

**What did you expect to happen:**

I would expect that logcheck will ignore this method when in `allow-unstructured` mode and report it as error only when `allow-unstructured` is off.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by luyou86**
#### 1. What type of PR is this?
/kind bug

#### 2. What this PR does / why we need it:
fix logcheck doesn't handle Exit* functions correctly

#### 3. Which issue(s) this PR fixes:
Fixes #264

#### 4. Does this PR introduce a user-facing change?
NONE

#### 5. Special notes for your reviewer:

### CODE REVIEW

File: hack/tools/logcheck/testdata/src/allowUnstructuredLogs/allowUnstructuredLogs.go [hunk 1]
```diff
@@ -41,6 +41,13 @@ func allowUnstructuredLogs() {
 	klog.ErrorS(nil, "Starting container in a pod", testKey, "containerID") // want `Key positional arguments are expected to be inlined constant strings. `
 	klog.InfoS("test: %s", "testname")                                      // want `structured logging function "InfoS" should not use format specifier "%s"`
 	klog.ErrorS(nil, "test no.: %d", 1)                                     // want `structured logging function "ErrorS" should not use format specifier "%d"`
+	klog.Exit("test log")
```
Comment (serathius) [inline hack/tools/logcheck/testdata/src/allowUnstructuredLogs/allowUnstructuredLogs.go:44]: Please move all those lines below section // Unstructed logs

File: hack/tools/logcheck/testdata/src/doNotAllowUnstructuredLogs/doNotAllowUnstructuredLogs.go [hunk 2]
```diff
@@ -41,6 +41,10 @@ func doNotAllowUnstructuredLogs() {
 	klog.ErrorS(nil, "Starting container in a pod", testKey, "containerID") // want `Key positional arguments are expected to be inlined constant strings. `
 	klog.InfoS("test: %s", "testname")                                      // want `structured logging function "InfoS" should not use format specifier "%s"`
 	klog.ErrorS(nil, "test no.: %d", 1)                                     // want `structured logging function "ErrorS" should not use format specifier "%d"`
+	klog.Exit("test log")
```
Comment (serathius) [inline hack/tools/logcheck/testdata/src/doNotAllowUnstructuredLogs/doNotAllowUnstructuredLogs.go:44]: Please move those lines under section //Unstructured logs

File: hack/tools/logcheck/testdata/src/doNotAllowUnstructuredLogs/doNotAllowUnstructuredLogs.go [hunk 3]
```diff
@@ -41,6 +41,10 @@ func doNotAllowUnstructuredLogs() {
...
+	klog.ExitDepth(1, "test log")
+	klog.Exitln("test log")
+	klog.Exitf("test log")
```
Comment (serathius) [inline hack/tools/logcheck/testdata/src/doNotAllowUnstructuredLogs/doNotAllowUnstructuredLogs.go:47]: Those lines should not be allowed, meaning they should have comment 
```
// want `unstructured logging function "Infof" should not be used`
```
Similar to lines below

File: hack/tools/logcheck/main.go [hunk 4]
```diff
@@ -179,11 +179,16 @@ func isKeysValid(keyValues []ast.Expr, fun ast.Expr, pass *analysis.Pass, funNam
...
 
-func checkForFormatSpecifier(expr *ast.CallExpr, pass *analysis.Pass) bool {
+func checkForFormatSpecifier(expr *ast.CallExpr, pass *analysis.Pass, c *config) bool {
 	if selExpr, ok := expr.Fun.(*ast.SelectorExpr); ok {
 		// extracting function Name like Infof
 		fName := selExpr.Sel.Name
-		if specifier, found := hasFormatSpecifier(expr.Args); found {
+		specifier, found := hasFormatSpecifier(expr.Args)
+		if found {
+			if (fName == "Exit" || fName ==  "Exitf" || fName == "Exitln" || fName == "ExitDepth") && c.allowUnstructured {
```
Comment (serathius) [inline hack/tools/logcheck/main.go:188]: Looks like your implementation was meant to allow always allow Exit* functions, but this is not what I intended.
We should treat Exit* functions same as other unstructured methods. Meaning that the fix should just update isUnstructured function to include Exit* functions.

Comment (luyou86) [reply hack/tools/logcheck/main.go:188]: i understand, i will modify it immediately
