### PR TITLE
Fix documentation for V(level)

### LINKED ISSUE #151: Documentation for `V()` appears to be backwards
/kind bug

**What steps did you take and what happened:**
Read the documentation and got confused by how `V()` works.

[It says](https://github.com/kubernetes/klog/blob/4cae117fdf5d65aeb3f638b8d8c87cd1cf8c8d41/klog.go#L1230-L1233) (for 2.0.0):

> If the level in the call to V is at least the value of -v, […] the V call will log.

This says that when the application is invoked with `-v 3`, then `V(4)` will log but `V(2)` will not.

The code actually says:
```golang
if logging.verbosity.get() >= level { … do logging … }
```

The is the opposite (`-v` is at least the value of `V()`), and is the typical interpretation for verbosity levels.

**What did you expect to happen:**

Given that the documentation says _at least_, I would expect that `V(n)` will log if `n` is greater than the value given on the command line.

**Anything else you would like to add:**
This appears to be carried over from `glog`.  Comparing against the C++ glog, that instead is documented from the other side; it has:

> `v` (`int`, default=0)
> Show all `VLOG(m)` messages for `m` less or equal the value of this flag.  Overridable by --vmodule.

Given the age of the comment, perhaps I'm just reading it weird? It may be a good idea to at least add examples to disambiguate the situation.

I'm happy to make a PR if people agree this is a thing that should be changed.

### PR DESCRIPTION
**Pull request by mook-as**
**What this PR does / why we need it**:
The documentation for `V(level)` was incorrect; it erroneously claimed that higher `V()` levels will get logged, whereas in reality lower levels will get logged.

**Which issue(s) this PR fixes**:
Fixes #151.

**Special notes for your reviewer**:
No functional change.  Nothing else in the file appears to warrant similar changes at a quick glance.
This appears to have been inherited from the initial commit for `glog`.

**Release note**:
```release-note
NONE
```

/kind documentation

### CODE REVIEW

File: klog.go [hunk 1]
```diff
@@ -1236,9 +1236,9 @@ func newVerbose(level Level, b bool) Verbose {
 // not evaluate its arguments.
 //
 // Whether an individual call to V generates a log record depends on the setting of
-// the -v and --vmodule flags; both are off by default. If the level in the call to
-// V is at least the value of -v, or of -vmodule for the source file containing the
-// call, the V call will log.
+// the -v and --vmodule flags; both are off by default. The V call with log if either
+// the value of -v is at least the level in the call to V, or if -vmodule matches the
+// source file containing the call.
```
Comment (neolit123) [inline klog.go:1241]: typo "with" / "will".

the statement is correct, yet this:

> -v is at least the level in the call to V

now reads as if -v depends on the level in V, which might confuse people as it's the other way around.

i'd phrase this like so:

> The V call will be logged if its level is less than or equal to the value of the -v flag, or alternatively if -vmodule matches the source file containing the call.

Comment (mook-as) [reply klog.go]: Thanks for taking a look!

Updated in c95db6fa890f878eebae871f8afa94d50f1bb11b — actually, expanded a bit too, since `-vmodule` actually provides a mapping of module to level, so _just_ matching the source file isn't correct.

**Comment by neolit123** [comment]
@mook-as 
LGTM, but please keep the commits squashed to one

**Comment by mook-as** [comment]
Thanks! Squashed.
