### PR TITLE
Fix goroutine leak: make flushDaemon stoppable

### LINKED ISSUE #188: go routine created on flush logs has a leak.
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
After running test cases found out that there is a go routine leak in klog.go
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 19 in state chan receive, with github.ibm.com/riaas/regional-storage/vendor/k8s.io/klog.(*loggingT).flushDaemon on top of the stack:
goroutine 19 [chan receive]:
github.ibm.com/riaas/regional-storage/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x240e2c0)
	/Users/himanshuchaudhary/go/src/github.ibm.com/riaas/regional-storage/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by github.ibm.com/riaas/regional-storage/vendor/k8s.io/klog.init.0
	/Users/himanshuchaudhary/go/src/github.ibm.com/riaas/regional-storage/vendor/k8s.io/klog/klog.go:411 +0xd6
```

### LINKED ISSUE #282: go routine created on flush logs leaks
/kind bug

**What steps did you take and what happened:**
uber/goleak found a leaking goroutine during test run:
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 19 in state chan receive, with k8s.io/klog/v2.(*loggingT).flushDaemon on top of the stack:
goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	/home/katexochen/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1181 +0x8b
created by k8s.io/klog/v2.init.0
	/home/katexochen/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:420 +0x1c5
]
```
Previous mentioned in #188.
#190 tried to fix this.
I'm opening a new issue since both are closed now but the problem still exists.

### PR DESCRIPTION
**Pull request by katexochen**
**What this PR does / why we need it**:
Previously, klog's init function started a goroutine to continuously flush buffers. This goroutine couldn't be stopped and made a shutdown without leaking goroutines impossible.

This PR makes it possible to stop and test the flushDaemon. It adds an API function so users can stop the daemon as well.

There was a previous attempt to fix this issue by someone else in #190. 

In #190, [someone requested to add goleak](https://github.com/kubernetes/klog/pull/190#issuecomment-731287436) to detect leaking goroutines in the future, so this PR introduces such validation.

**Which issue(s) this PR fixes**:
fixes #282, fixes #188

**Release note**:

```release-note
Make flushDaemon stoppable to prevent goroutine leak
```

### CODE REVIEW

File: klog_test.go [hunk 1]
```diff
@@ -35,11 +35,24 @@ import (
 	"time"
 
 	"github.com/go-logr/logr"
+	"go.uber.org/goleak"
```
Comment (pohly) [inline klog_test.go:38]: We can't have `go.uber.org/goleak` as dependency of klog itself.

You can create an `examples/flushing` directory where you provide a `main.go` file which shows how to use the new API and a test that uses `goleak`.

Comment (katexochen) [reply klog_test.go:38]: Sure, I already thought so. I'll move this in into a separate directory.

File: klog.go [hunk 2]
```diff
@@ -1290,10 +1295,70 @@ func (l *loggingT) createFiles(sev severity) error {
...
+	return &flushDaemon{
+		interval: interval,
+		flush:    flush,
+	}
+}
+
+// run starts a goroutine that periodically calls the daemons flush function.
+// Calling run on an already running daemon will have no effect.
+func (f *flushDaemon) run() {
+	if f.isRunning() {
```
Comment (pohly) [inline klog.go:1316]: Some more code and/or documentation is needed to ensure that this code is thread-safe.

As it stands now, the user might call `StopFlushDaemon` while the daemon is being started. Not very likely, but still...

We can probably require that `logging.mu` must be held when calling `run`, `stop` or `isRunning` and then lock that mutex in `StopFlushDaemon`.

File: klog.go [hunk 3]
```diff
@@ -1290,10 +1295,70 @@ func (l *loggingT) createFiles(sev severity) error {
...
+	f.stopDone = make(chan struct{}, 1)
+
+	go func() {
+		ticker := time.NewTicker(f.interval)
+		for {
+			select {
+			case <-ticker.C:
+				f.flush()
+			case <-f.stopC:
+				ticker.Stop()
```
Comment (pohly) [inline klog.go:1330]: nit: I prefer to have this in a `defer` directly after setting up the ticker.

File: klog.go [hunk 4]
```diff
@@ -1290,10 +1295,70 @@ func (l *loggingT) createFiles(sev severity) error {
...
+				f.stopDone <- struct{}{}
```
Comment (pohly) [inline klog.go:1331]: nit: also a candidate for a `defer`.

**Review by pohly — COMMENTED** [review]
> it was my intention to stick to your suggestion. Maybe I misunderstood your proposal.

No, you got it right. I just didn't read the entire PR and didn't see that `newFlushDaemon` doesn't start a goroutine.

**Comment by pohly** [comment]
BTW, as far as I am concerned you can squash right away and force-push a single commit. Then we can merge it right away when it is done.

File: klog.go (hunk 2 above)
Comment (katexochen) [reply klog.go]: I'd prefer to lock the flushDaemon separate from the loggingT, by giving the daemon its own mutex. This way, flushDaemon can do the locking itself, which reduces complexity for the caller.

Comment (pohly) [reply klog.go]: I agree, this better. I was worried that `run` might be called frequently, but because `createFile` itself is under an if check, that won't be the case.

File: examples/flushing/flushing_test.go [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+	klog.StopFlushDaemon()
+
+	// After you stopped the flushDaemon, you can still manually flush.
+	klog.Info("bye")
+	klog.Flush()
+}
+
+func TestLeakingFlushDaemon(t *testing.T) {
+	// goleak detects leaking goroutines.
+	defer goleak.VerifyNone(t)
```
Comment (pohly) [inline examples/flushing/flushing_test.go:35]: Not a problem with the code, I am just wondering: is this check racy?

The usual pattern for shutting down a goroutine is what you have implemented: the goroutine itself notifies the main goroutine that it is done, then returns from its function. But if the main goroutine then immediately wakes up (can that happen?) and checks for the existence of the goroutine, it might still find it because the goroutine is still in the process of terminating itself (or getting terminated).

In other languages there is an explicit "join thread", but not in Go. That's not normally a problem because once the goroutine function is ready to return, it doesn't do anything anymore and whether it still exists doesn't matter. But here it does :man_shrugging:

**Review by pohly — APPROVED** [review]
/lgtm

/assign @dims 

Still needs ok-to-test, it looks like I can't add that.

File: examples/flushing/flushing_test.go (hunk 5 above)
Comment (katexochen) [reply examples/flushing/flushing_test.go:35]: Good question, I've never thought about this. It seems like they just sleep and retry if there are still goroutines running. https://github.com/uber-go/goleak/blob/421b885faf413a221d1a86a17684fb3c45bd35c5/leaks.go#L60-L67

Comment (pohly) [reply examples/flushing/flushing_test.go:35]: So it looks like this can happen, and goleak deals with it. Good :smile:

File: klog.go [hunk 6]
```diff
@@ -1022,6 +1024,9 @@ const bufferSize = 256 * 1024
 // createFiles creates all the log files for severity from sev down to infoLog.
 // l.mu is held.
 func (l *loggingT) createFiles(sev severity.Severity) error {
+	if l.flushD != nil {
```
Comment (thockin) [inline klog.go:1027]: under what conditions would this be nil?

**Review by thockin — COMMENTED** [review]
No objections

File: klog.go (hunk 6 above)
Comment (katexochen) [reply klog.go:1027]: I guess it shouldn't happen during normal operation, I will remove the check.

**Comment by katexochen** [comment]
Since `TestFlushDaemon` failed, I've increased the sleep duration to give the flushDaemon more time to start and lowered the expected flush count.

File: klog.go [hunk 7]
```diff
@@ -1042,10 +1045,79 @@ func (l *loggingT) createFiles(sev severity.Severity) error {
...
+
+	go func() {
+		ticker := time.NewTicker(f.interval)
+		defer ticker.Stop()
+		defer func() { f.stopDone <- struct{}{} }()
+		for {
+			select {
+			case <-ticker.C:
+				f.flush()
+			case <-f.stopC:
```
Comment (thockin) [inline klog.go:1085]: Should this flush() one last time?

File: klog_test.go [hunk 8]
```diff
@@ -1852,3 +1856,38 @@ func (s *structWithLock) addWithDefer() {
...
+		testLog := loggingT{flushD: newFlushDaemon(10*time.Millisecond, spyFunc)}
+
+		// Calling testLog will call createFile, which should start the daemon.
+		testLog.print(sev, nil, nil, "x")
+
+		if !testLog.flushD.isRunning() {
+			t.Error("expected flushD to be running")
+		}
+
+		time.Sleep(400 * time.Millisecond)
```
Comment (thockin) [inline klog_test.go:1873]: Comment on why sleep?  This is usually a smell...

Comment (thockin) [reply klog_test.go:1873]: Or inject a fake ticket so you can manually "advance time" rather than sleep.  Deterministic tests FTW

File: klog.go (hunk 7 above)
Comment (katexochen) [reply klog.go:1085]: Yes, that would make sense.

File: klog_test.go (hunk 8 above)
Comment (katexochen) [reply klog_test.go:1873]: Thanks for your feedback. I'm not quite sure what you mean by "fake ticket". Did you mean ticker? I think the problem here is the startup time of the goroutine, not the flush interval, so I don't understand how a fake ticker could help with that.
But I agree that tests should be deterministic if possible and I'd be glad if you could give me some more hints on how to make it deterministic. :slightly_smiling_face:

Comment (thockin) [reply klog_test.go:1873]: Sorry, I meant "ticker".

e.g. staging/src/k8s.io/client-go/util/workqueue/rate_limiting_queue_test.go - it uses `testingclock.NewFakeClock` (k8s.io/utils/clock/testing) which has a `NewTicker` method.

Pass a `k8s.io/utils/clock.WithTicker` to `newFlushDaemon()` (passing `nil` means "use time.NewTicker()") and store that  in the `flushDaemon` struct.  In `run()` you can check if the passed-in `clock.WithTicker` is nil.  If so, do what this does now (use a real ticker) but if it is not nil, use it instead.

Then your test amnipulates the fake clock's time to cause ticks when you expect them.

As for the daemon startup - you already call isRunning(), so you know it's alive...

Comment (katexochen) [reply klog_test.go]: I've added the clock, thanks for the great tip.
In addition, I had to move the creation of the ticker out of the go function and add a channel for communication between the spy function and the test.

File: klog_test.go [hunk 9]
```diff
@@ -1852,3 +1857,48 @@ func (s *structWithLock) addWithDefer() {
...
 	s.n++
 }
+
+func TestFlushDaemon(t *testing.T) {
+	for sev := severity.InfoLog; sev < severity.FatalLog; sev++ {
+		flushed := make(chan struct{}, 1)
+		spyFunc := func() {
+			flushed <- struct{}{}
+		}
+		testClock := testingclock.NewFakeClock(time.Now())
```
Comment (thockin) [inline klog_test.go:1867]: call `newFlushDaemon(time.Millisecond, spyFunc, testClock)`

File: klog_test.go [hunk 10]
```diff
@@ -1852,3 +1857,48 @@ func (s *structWithLock) addWithDefer() {
...
+
+		// Calling testLog will call createFile, which should start the daemon.
+		testLog.print(sev, nil, nil, "x")
+
+		if !testLog.flushD.isRunning() {
+			t.Error("expected flushD to be running")
+		}
+
+		testClock.Step(time.Second)
+		<-flushed
```
Comment (thockin) [inline klog_test.go:1884]: Should this be verifying something?  What happens if there was a bug and flush-daemon did not call the func properly, what would this test report?

Comment (katexochen) [reply klog_test.go:1884]: The statement verifies that flush was called and let's the test wait until the flush execution finished. If the function isn't called, the test will time out. If I don't wait for the function here, the `testClock.Step()` statements will be all executed directly after each other, without flushDaemon having time to flush in between, so the flushDaemon would only enter the `case <-ticker.C()` once, regardless of how many steps the clock does.

Comment (thockin) [reply klog_test.go:1880]: What I meant is maybe we should control the timeout and produce an error ourselves.  The default is something like 10 minutes, right?  It seems like we could wrap these reads in a timeout of 10 seconds and produce a better error.

**Review by thockin — COMMENTED** [review]
I'm going to go ahead an approve - my last comment is pretty incremental :)

/approve
/lgtm

File: go.mod [hunk 11]
```diff
@@ -2,4 +2,7 @@ module k8s.io/klog/v2
 
 go 1.13
 
-require github.com/go-logr/logr v1.2.0
+require (
+	github.com/go-logr/logr v1.2.0
+	k8s.io/utils v0.0.0-20220210201930-3a6ce19ff2f9
```
Comment (liggitt) [inline go.mod:7]: this adds a circular dependency... utils already depends on klog, we should avoid making klog also depend on utils

Comment (pohly) [reply go.mod:7]: I think the test is useful enough that we should not remove it and instead carry a copy of the clock code -> https://github.com/kubernetes/klog/pull/310

**Comment by thockin** [comment]
More reasons to break up utils further.
